language: en-US
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  review_progress: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
